<?php

$sql = 

"CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cognome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Mazzo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    carte JSON NOT NULL
);
";


/**
 DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS mazzo;
CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cognome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS mazzo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    query_string VARCHAR(512) NOT NULL,
    carte JSON NOT NULL
);

 */